version: '1.0'

  
services:
  sqlserver:
    image: 2022-latest
    container_name: mssql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - docker/database:var/lib/mssql_server
  appUserJava: