CREATE TABLE Doctors (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    UserId UNIQUEIDENTIFIER NOT NULL,
    DisplayName NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX),
    ClinicAddress NVARCHAR(255) NOT NULL,
    ClinicCity NVARCHAR(100) NOT NULL,
    Specialization NVARCHAR(100) NOT NULL,
    NumberOfAppointments INT DEFAULT 0,
    NumberOfVideoCalls INT DEFAULT 0,
    HistoryOfWork NVARCHAR(MAX) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES user(Id)
);

CREATE TABLE UserReports (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    ReporterId UNIQUEIDENTIFIER NOT NULL,
    ReportType NVARCHAR(100) NOT NULL,
    ReportDescription NVARCHAR(MAX) NOT NULL,
    ReportedId UNIQUEIDENTIFIER NOT NULL,
    Status INT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    ResolvedAt DATETIME NULL,
    FOREIGN KEY (ReporterId) REFERENCES user(Id)
);
