server:
  port: 9090
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:sqlserver://gitznoz.database.windows.net:1433;database=DOAN;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sas
    password: Hoang351681442002
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      show-sql: true
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: "duongnthn2312@gmail.com"
    password: "hfbz zxhp qbjt ripu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: "U5IeSrMYMWbhjirxzw/OeuPWRgdWPSGueiQVa8Bn5+VSxDx0vDvH0l4fsl1p2EOk"
  valid-duration: 1 #days
  refreshable-duration: 2 #days
