using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Models.Entities
{
    /// <summary>
    /// Represents an image entity that stores metadata about an uploaded image.
    /// </summary>
	public class Image
	{
		/// <summary>
        /// Gets or sets the unique identifier for the image.
        /// </summary>
        /// <remarks>
        /// This property is auto-generated by the database.
        /// </remarks>
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int Id { get; set; }

		/// <summary>
        /// Gets or sets the URL where the image is stored.
        /// </summary>
		[Required]
		public required string ImageUrl { get; set; }

        /// <summary>
        /// Gets or sets the public identifier for the image.
        /// </summary>
		[Required]
		public required string PublicId { get; set; }
	}
}
